// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package readingdb

import (
	"time"

	"github.com/anthonyvsmuller/quire/internal/shared/crdt"
	"uuid"
)

type ReadingAnnotation struct {
	ID          uuid.UUID
	EbookID     uuid.UUID
	DeviceID    *uuid.UUID
	Kind        string
	Text        *string
	Locator     string
	VectorClock crdt.VectorClock
	UpdatedAt   time.Time
	Deleted     bool
}

type ReadingProgress struct {
	ID          uuid.UUID
	EbookID     uuid.UUID
	DeviceID    uuid.UUID
	Locator     string
	Percent     *float64
	VectorClock crdt.VectorClock
	UpdatedAt   time.Time
}
