// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package readingdb

import (
	"context"

	"uuid"
)

type Querier interface {
	// What a reader has written in a work (RF03, UC04).
	//
	// Nothing here is scoped to a reader, and unlike the library slice that is not
	// an omission the statements make up for: reading.annotations references the
	// work and not the reader, so who a mark belongs to is a question about the
	// work it is in. Every use case asks that question first, of the library
	// slice's repository, and only then addresses a mark — which is why the
	// statements below take an identifier and a work rather than an identifier and
	// a reader.
	//
	// The four replication columns are written by the application and never by a
	// trigger, for the reason C01 gives: a trigger would overwrite the authoring
	// device's timestamp with the local now() as the operation was applied, and an
	// old write from a device that had been offline would beat a newer local one.
	CreateAnnotation(ctx context.Context, arg CreateAnnotationParams) error
	// Where each device stopped in each work (RF02, RN01; UC05).
	//
	// One row per work and device, which progress_ebook_device_key enforces and
	// C05 in docs/tcc-corrections.md is about. The pair is how every statement
	// addresses the row: the identifier exists to be what a synchronization
	// operation names, and nothing here looks a position up by it.
	//
	// There is no statement that removes a row and none that tombstones one. A
	// reader who stops reading a work leaves their position where it was, and the
	// row goes when the work goes, by the cascade the schema declares.
	//
	// Two replication columns rather than four, and that is the whole of C05 in
	// the schema: the row has one writer, so the device whose write it reflects is
	// already its own key and there is no tie to break. The clock is a version
	// counter for deduplication during replication, not a conflict resolver.
	CreateProgress(ctx context.Context, arg CreateProgressParams) error
	// Tombstoned or not, because the caller is the one that knows what it is for:
	// a reader asking to see the mark is answered that there is none, and a reader
	// asking to delete it again is answered that it is already gone.
	GetAnnotationByID(ctx context.Context, id uuid.UUID) (ReadingAnnotation, error)
	// Where one device stopped in one work. No row is a work that device has never
	// opened, which the caller answers by recording a first position rather than
	// by failing.
	GetProgressByPair(ctx context.Context, arg GetProgressByPairParams) (ReadingProgress, error)
	// One page of what was written in one work, ordered by the identifier.
	//
	// The identifier is the whole of the ordering and the whole of the keyset, and
	// it is the only column that could be either. Quadro 22 gives an annotation no
	// creation instant, and updated_at is rewritten by every edit, so a page
	// ordered by either would skip or repeat a mark that a second device edited
	// between two requests — which is the failure keyset pagination exists to
	// remove, arriving through the sort key instead of through the offset.
	//
	// The order is therefore stable rather than meaningful. Where a mark sits in a
	// book is a property of the document, which the client can resolve and this
	// node cannot; what the statement guarantees is that a client walking every
	// page sees every mark exactly once, which is what it needs in order to sort
	// them itself.
	//
	// annotations_ebook_id_id_idx serves the whole statement: the work selects,
	// the ordering is the index order, and the cursor is a seek into it.
	ListAnnotations(ctx context.Context, arg ListAnnotationsParams) ([]ReadingAnnotation, error)
	// Every device's position in one work (RN01), which is what a client needs in
	// order to decide what to show the reader: the furthest position, the most
	// recent one, or a prompt asking which to resume from. That decision belongs
	// to the client, so this does not make it by returning one row.
	//
	// It is not paginated, and the bound is the reader's own: there is one row per
	// appliance they have ever read the work on. The ordering is by device so that
	// two calls return the same list in the same order, which a client diffing
	// against what it already showed depends on.
	//
	// progress_ebook_device_key serves it: the pair is unique, so the constraint's
	// index leads with the work and is already in device order within it.
	ListProgressForEbook(ctx context.Context, ebookID uuid.UUID) ([]ReadingProgress, error)
	// Everything UC04 edits, and the revision the write stamped.
	//
	// The tombstone is written here rather than by a statement of its own, because
	// a deletion is a write like any other: it carries a vector clock, a timestamp
	// and the device that made it, and a DELETE would carry none of the three —
	// the mark would be resurrected by the next node that had not yet heard about
	// it.
	//
	// The work is not in the SET list. A mark is made in a work and stays in it; a
	// note that moved between books would be a note about a passage that is not
	// there.
	UpdateAnnotation(ctx context.Context, arg UpdateAnnotationParams) (int64, error)
	// Where the device has reached now, and the version the write stamped.
	//
	// Neither half of the natural key is in the SET list. A position belongs to
	// one work and one device for as long as it exists, and a statement that could
	// move it to another would be a statement that could move another device's
	// bookmark.
	UpdateProgress(ctx context.Context, arg UpdateProgressParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
