// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deliveries.sql

package syncdb

import (
	"context"
	"time"

	"uuid"
)

const confirmDeliveries = `-- name: ConfirmDeliveries :execrows
UPDATE sync.deliveries
SET applied_at      = $1,
    attempts        = attempts + 1,
    last_attempt_at = $1,
    last_error      = NULL
WHERE server_id = $2
  AND operation_id = ANY ($3::uuid[])
  AND applied_at IS NULL
`

type ConfirmDeliveriesParams struct {
	AttemptedAt  *time.Time
	ServerID     uuid.UUID
	OperationIds []uuid.UUID
}

// Close the deliveries of one batch that the destination confirmed.
//
// Already-confirmed rows are excluded rather than rewritten, so a reply that
// arrives twice does not count a second attempt or move the instant the
// operation was applied at.
func (q *Queries) ConfirmDeliveries(ctx context.Context, arg ConfirmDeliveriesParams) (int64, error) {
	result, err := q.db.Exec(ctx, confirmDeliveries, arg.AttemptedAt, arg.ServerID, arg.OperationIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enqueueDeliveries = `-- name: EnqueueDeliveries :exec

INSERT INTO sync.deliveries (operation_id, server_id)
SELECT $1, unnest($2::uuid[])
ON CONFLICT (operation_id, server_id) DO NOTHING
`

type EnqueueDeliveriesParams struct {
	OperationID uuid.UUID
	ServerIds   []uuid.UUID
}

// What this node still owes its peers, one row per operation and destination
// (MER: entrega_sync, the entity C07 in docs/tcc-corrections.md splits out of
// operacao_sync).
//
// The table is a queue and not a history. A row exists because a change has to
// reach a node and has not yet; what closes it is the destination's own
// confirmation, which is safe to act on precisely because receiving is
// idempotent by operation identifier — a delivery retried after a reply that
// was lost costs one call and changes nothing there.
// Owe an operation to each of the nodes.
//
// The pair is unique, so a second enqueue of the same pair does nothing: the
// statement is written to be safe under the retry the transaction manager
// performs after a serialization failure, and under an operation that arrives
// again from a second peer.
//
// It must run in the transaction that appended the operation. A change
// committed without its delivery rows is a change no worker will ever send,
// and nothing afterwards would notice.
func (q *Queries) EnqueueDeliveries(ctx context.Context, arg EnqueueDeliveriesParams) error {
	_, err := q.db.Exec(ctx, enqueueDeliveries, arg.OperationID, arg.ServerIds)
	return err
}

const failDeliveries = `-- name: FailDeliveries :execrows
UPDATE sync.deliveries
SET attempts        = attempts + 1,
    last_attempt_at = $1,
    last_error      = $2
WHERE server_id = $3
  AND operation_id = ANY ($4::uuid[])
  AND applied_at IS NULL
`

type FailDeliveriesParams struct {
	AttemptedAt  *time.Time
	Reason       *string
	ServerID     uuid.UUID
	OperationIds []uuid.UUID
}

// Count a try that did not land, and record what it said.
//
// The count is what the backoff above is computed from, which is why a worker
// must record a failure rather than merely logging it: a failure nobody
// counted is a peer retried at full rate for ever.
func (q *Queries) FailDeliveries(ctx context.Context, arg FailDeliveriesParams) (int64, error) {
	result, err := q.db.Exec(ctx, failDeliveries,
		arg.AttemptedAt,
		arg.Reason,
		arg.ServerID,
		arg.OperationIds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listPendingDeliveries = `-- name: ListPendingDeliveries :many
SELECT id, operation_id, server_id, applied_at, attempts, last_attempt_at, last_error
FROM sync.deliveries
WHERE server_id = $1
  AND applied_at IS NULL
  AND (last_attempt_at IS NULL
       OR last_attempt_at < $2::timestamptz
            - $3::double precision
              * power(2, least(attempts, $4::integer))
              * interval '1 second')
ORDER BY last_attempt_at NULLS FIRST, id
LIMIT $5::integer
`

type ListPendingDeliveriesParams struct {
	ServerID       uuid.UUID
	Now            time.Time
	BackoffSeconds float64
	MaxExponent    int32
	PageSize       int32
}

// What is still owed to one node, oldest attempt first.
//
// The backoff is in the predicate rather than in the worker, because the
// alternative is reading rows in order to skip them: a peer that has been
// unreachable for a week has every one of its rows waiting, and a worker that
// filtered in Go would page through all of them on every tick. Doubling once
// per attempt is bounded by the caller, which passes the exponent ceiling.
//
// deliveries_pending_idx serves the ordering and the destination, and its
// partial predicate keeps it the size of the backlog rather than of the
// history.
func (q *Queries) ListPendingDeliveries(ctx context.Context, arg ListPendingDeliveriesParams) ([]SyncDelivery, error) {
	rows, err := q.db.Query(ctx, listPendingDeliveries,
		arg.ServerID,
		arg.Now,
		arg.BackoffSeconds,
		arg.MaxExponent,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SyncDelivery{}
	for rows.Next() {
		var i SyncDelivery
		if err := rows.Scan(
			&i.ID,
			&i.OperationID,
			&i.ServerID,
			&i.AppliedAt,
			&i.Attempts,
			&i.LastAttemptAt,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingServers = `-- name: ListPendingServers :many
SELECT DISTINCT server_id
FROM sync.deliveries
WHERE applied_at IS NULL
`

// The nodes this instance owes anything to at all.
//
// The worker asks this rather than walking the catalogue, because the two are
// different sets: a node authorized a moment ago is owed nothing yet, and a
// node whose authorization was revoked may still be owed what was enqueued
// before the revocation.
func (q *Queries) ListPendingServers(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listPendingServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var server_id uuid.UUID
		if err := rows.Scan(&server_id); err != nil {
			return nil, err
		}
		items = append(items, server_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
