// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deliveries.sql

package syncdb

import (
	"context"
	"time"

	"uuid"
)

const confirmDeliveries = `-- name: ConfirmDeliveries :execrows
UPDATE sync.deliveries
SET applied_at      = $1,
    attempts        = attempts + 1,
    last_attempt_at = $1,
    last_error      = NULL
WHERE server_id = $2
  AND operation_id = ANY ($3::uuid[])
  AND applied_at IS NULL
`

type ConfirmDeliveriesParams struct {
	AttemptedAt  *time.Time
	ServerID     uuid.UUID
	OperationIds []uuid.UUID
}

// Close the deliveries of one batch that the destination confirmed.
//
// Already-confirmed rows are excluded rather than rewritten, so a reply that
// arrives twice does not count a second attempt or move the instant the
// operation was applied at.
func (q *Queries) ConfirmDeliveries(ctx context.Context, arg ConfirmDeliveriesParams) (int64, error) {
	result, err := q.db.Exec(ctx, confirmDeliveries, arg.AttemptedAt, arg.ServerID, arg.OperationIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enqueueDeliveries = `-- name: EnqueueDeliveries :exec

INSERT INTO sync.deliveries (operation_id, server_id)
SELECT $1, unnest($2::uuid[])
ON CONFLICT (operation_id, server_id) DO NOTHING
`

type EnqueueDeliveriesParams struct {
	OperationID uuid.UUID
	ServerIds   []uuid.UUID
}

// What this node still owes its peers, one row per operation and destination
// (MER: entrega_sync, the entity C07 in docs/tcc-corrections.md splits out of
// operacao_sync).
//
// The table is a queue and not a history. A row exists because a change has to
// reach a node and has not yet; what closes it is the destination's own
// confirmation, which is safe to act on precisely because receiving is
// idempotent by operation identifier — a delivery retried after a reply that
// was lost costs one call and changes nothing there.
// Owe an operation to each of the nodes.
//
// The pair is unique, so a second enqueue of the same pair does nothing: the
// statement is written to be safe under the retry the transaction manager
// performs after a serialization failure, and under an operation that arrives
// again from a second peer.
//
// It must run in the transaction that appended the operation. A change
// committed without its delivery rows is a change no worker will ever send,
// and nothing afterwards would notice.
func (q *Queries) EnqueueDeliveries(ctx context.Context, arg EnqueueDeliveriesParams) error {
	_, err := q.db.Exec(ctx, enqueueDeliveries, arg.OperationID, arg.ServerIds)
	return err
}

const enqueuePendingDeliveries = `-- name: EnqueuePendingDeliveries :execrows
INSERT INTO sync.deliveries (operation_id, server_id)
SELECT o.id, r.server_id
FROM federation.user_replicas r
    JOIN federation.servers s ON s.id = r.server_id
    JOIN sync.operations o ON o.user_id = r.user_id
WHERE r.active
  AND s.active
  AND NOT s.is_local
  AND o.position > COALESCE((
      SELECT max(owed.position)
      FROM sync.deliveries d
          JOIN sync.operations owed ON owed.id = d.operation_id
      WHERE d.server_id = r.server_id
        AND owed.user_id = r.user_id
  ), 0)
ON CONFLICT (operation_id, server_id) DO NOTHING
`

// Owe every peer everything the reader has authorized it for and it has not
// been offered yet.
//
// This is where the queue is filled, and it is filled here rather than by the
// call that stored the operation, for a reason that only shows up on the second
// peer. A node authorized as a replica today holds none of the reader's history
// (RF16, UC15), and rows written when the change happened would carry only what
// happened afterwards — the peer would be permanently missing everything from
// before its own authorization, and nothing would ever notice. Filling the
// queue from the log instead makes the two cases one: a peer authorized a
// moment ago and a peer that missed a week are both simply owed what they have
// not been offered.
//
// The subquery is the watermark that keeps it from being a scan of the whole
// log on every tick. Deliveries are enqueued in position order and never
// skipped, so the highest position already owed to a pair is a floor for what
// is left, and the ON CONFLICT is what makes the statement safe when it is not.
//
// This node's own row is excluded, and so is a peer discovery has learned about
// but the operator has stopped: an inactive node keeps what it already owes and
// is offered nothing new.
func (q *Queries) EnqueuePendingDeliveries(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, enqueuePendingDeliveries)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failDeliveries = `-- name: FailDeliveries :execrows
UPDATE sync.deliveries
SET attempts        = attempts + 1,
    last_attempt_at = $1,
    last_error      = $2
WHERE server_id = $3
  AND operation_id = ANY ($4::uuid[])
  AND applied_at IS NULL
`

type FailDeliveriesParams struct {
	AttemptedAt  *time.Time
	Reason       *string
	ServerID     uuid.UUID
	OperationIds []uuid.UUID
}

// Count a try that did not land, and record what it said.
//
// The count is what the backoff above is computed from, which is why a worker
// must record a failure rather than merely logging it: a failure nobody
// counted is a peer retried at full rate for ever.
func (q *Queries) FailDeliveries(ctx context.Context, arg FailDeliveriesParams) (int64, error) {
	result, err := q.db.Exec(ctx, failDeliveries,
		arg.AttemptedAt,
		arg.Reason,
		arg.ServerID,
		arg.OperationIds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listPendingDeliveries = `-- name: ListPendingDeliveries :many
SELECT d.id, d.operation_id, d.server_id, d.applied_at, d.attempts, d.last_attempt_at, d.last_error
FROM sync.deliveries d
    JOIN sync.operations o ON o.id = d.operation_id
WHERE d.server_id = $1
  AND d.applied_at IS NULL
  AND (d.last_attempt_at IS NULL
       OR d.last_attempt_at < $2::timestamptz
            - $3::double precision
              * power(2, least(d.attempts, $4::integer))
              * interval '1 second')
ORDER BY last_attempt_at NULLS FIRST, o.user_id, o.position
LIMIT $5::integer
`

type ListPendingDeliveriesParams struct {
	ServerID       uuid.UUID
	Now            time.Time
	BackoffSeconds float64
	MaxExponent    int32
	PageSize       int32
}

// What is still owed to one node, oldest attempt first and then in log order.
//
// The backoff is in the predicate rather than in the worker, because the
// alternative is reading rows in order to skip them: a peer that has been
// unreachable for a week has every one of its rows waiting, and a worker that
// filtered in Go would page through all of them on every tick. Doubling once
// per attempt is bounded by the caller, which passes the exponent ceiling.
//
// The order is the log's and not the queue's, and the join is what buys it: a
// peer is offered a reader's changes in the order this node committed them, so
// a batch cannot carry an update ahead of the insert it depends on — which the
// reconciler at the far end would refuse outright. The row identifier would
// have been the cheap tie-break and is exactly the wrong one: it is a random
// uuid, so it would have shuffled a reader's history into an order no node
// could apply.
//
// deliveries_pending_idx serves the destination and the backoff, and its
// partial predicate keeps it the size of the backlog rather than of the
// history.
func (q *Queries) ListPendingDeliveries(ctx context.Context, arg ListPendingDeliveriesParams) ([]SyncDelivery, error) {
	rows, err := q.db.Query(ctx, listPendingDeliveries,
		arg.ServerID,
		arg.Now,
		arg.BackoffSeconds,
		arg.MaxExponent,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SyncDelivery{}
	for rows.Next() {
		var i SyncDelivery
		if err := rows.Scan(
			&i.ID,
			&i.OperationID,
			&i.ServerID,
			&i.AppliedAt,
			&i.Attempts,
			&i.LastAttemptAt,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingServers = `-- name: ListPendingServers :many
SELECT DISTINCT server_id
FROM sync.deliveries
WHERE applied_at IS NULL
`

// The nodes this instance owes anything to at all.
//
// The worker asks this rather than walking the catalogue, because the two are
// different sets: a node authorized a moment ago is owed nothing yet, and a
// node whose authorization was revoked may still be owed what was enqueued
// before the revocation.
func (q *Queries) ListPendingServers(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listPendingServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var server_id uuid.UUID
		if err := rows.Scan(&server_id); err != nil {
			return nil, err
		}
		items = append(items, server_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
