// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operations.sql

package syncdb

import (
	"context"
	"encoding/json"
	"time"

	"github.com/anthonyvsmuller/quire/internal/shared/crdt"
	"uuid"
)

const appendOperation = `-- name: AppendOperation :one

WITH allocated AS (
    INSERT INTO sync.streams (user_id, last_position)
    VALUES ($2, 1)
    ON CONFLICT (user_id) DO UPDATE
        SET last_position = sync.streams.last_position + 1
    RETURNING last_position
)
INSERT INTO sync.operations (id, user_id, device_id, position, target_entity, target_id,
                             operation, delta, vector_clock, created_at)
SELECT $1, $2, $3, allocated.last_position,
       $4, $5, $6,
       $7, $8, $9
FROM allocated
ON CONFLICT (id) DO NOTHING
RETURNING position
`

type AppendOperationParams struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	DeviceID     uuid.UUID
	TargetEntity string
	TargetID     uuid.UUID
	Operation    string
	Delta        json.RawMessage
	VectorClock  crdt.VectorClock
	CreatedAt    time.Time
}

// The log of changes this node holds for its readers (RF10, RF12; UC09, UC11).
//
// Three properties hold across every statement here and are what make the rest
// of them small.
//
// The identifier is the author's. A device mints it and it is the same uuid on
// every node that ever sees the operation, so receiving is an
// INSERT ... ON CONFLICT (id) DO NOTHING and no statement here generates one.
//
// The position is this node's. It is allocated from sync.streams inside the
// writing transaction, and the whole of C08 in docs/tcc-corrections.md is why
// it has to be: the row lock is held until commit, so a second writer cannot
// obtain its number before the first has committed, and the order of the
// numbers is therefore the order of the commits rather than the order of the
// inserts.
//
// The log is append-only. Nothing here updates a row; what changes is the
// delivery rows that point at it, which are in deliveries.sql.
// Store an operation, allocating this node's position for it in the same
// statement.
//
// The allocation is a data-modifying CTE rather than a separate call, and that
// is what makes C08's requirement structural instead of a comment somebody has
// to obey: a statement cannot straddle two transactions, so the lock the upsert
// takes cannot be released before the operation it numbered is visible.
//
// A duplicate returns no row, which is how the caller learns that this node
// already had the operation. It consumes a position doing so, and the gap that
// leaves is expected and harmless — the cursor is a lower bound on what has
// been seen, not a count of what exists.
func (q *Queries) AppendOperation(ctx context.Context, arg AppendOperationParams) (int64, error) {
	row := q.db.QueryRow(ctx, appendOperation,
		arg.ID,
		arg.UserID,
		arg.DeviceID,
		arg.TargetEntity,
		arg.TargetID,
		arg.Operation,
		arg.Delta,
		arg.VectorClock,
		arg.CreatedAt,
	)
	var position int64
	err := row.Scan(&position)
	return position, err
}

const listOperationsAfter = `-- name: ListOperationsAfter :many
SELECT id, user_id, device_id, position, target_entity, target_id, operation, delta,
       vector_clock, created_at
FROM sync.operations
WHERE user_id = $1
  AND position > $2
ORDER BY position
LIMIT $3::integer
`

type ListOperationsAfterParams struct {
	UserID        uuid.UUID
	AfterPosition int64
	PageSize      int32
}

// One page of a reader's log, in the order this node committed it (RN06).
//
// The cursor is a position and not a timestamp, for the reason C08 gives: an
// operation stamped early and committed late is skipped by a cursor that has
// already moved past it, and it is not delayed, it is lost.
//
// operations_user_position_idx serves the whole statement: the reader selects,
// the ordering is the index order, and the cursor is a seek into it.
func (q *Queries) ListOperationsAfter(ctx context.Context, arg ListOperationsAfterParams) ([]SyncOperation, error) {
	rows, err := q.db.Query(ctx, listOperationsAfter, arg.UserID, arg.AfterPosition, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SyncOperation{}
	for rows.Next() {
		var i SyncOperation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceID,
			&i.Position,
			&i.TargetEntity,
			&i.TargetID,
			&i.Operation,
			&i.Delta,
			&i.VectorClock,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperationsByID = `-- name: ListOperationsByID :many
SELECT id, user_id, device_id, position, target_entity, target_id, operation, delta,
       vector_clock, created_at
FROM sync.operations
WHERE id = ANY ($1::uuid[])
ORDER BY user_id, position
`

// The operations a batch of deliveries owes, by the identifiers their authors
// minted.
//
// The order is the reader and then the position, because the caller sends them
// grouped by reader: the peer-facing call names one reader, since the
// certificate identifies the node and not any of the readers it replicates.
func (q *Queries) ListOperationsByID(ctx context.Context, ids []uuid.UUID) ([]SyncOperation, error) {
	rows, err := q.db.Query(ctx, listOperationsByID, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SyncOperation{}
	for rows.Next() {
		var i SyncOperation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceID,
			&i.Position,
			&i.TargetEntity,
			&i.TargetID,
			&i.Operation,
			&i.Delta,
			&i.VectorClock,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
