// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package federationdb

import (
	"time"

	"uuid"
)

type FederationServer struct {
	ID                     uuid.UUID
	Domain                 string
	BaseUrl                string
	JwksUri                *string
	CertificateFingerprint *string
	IsLocal                bool
	DiscoveredAt           *time.Time
	Active                 bool
}

type FederationUserReplica struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	ServerID        uuid.UUID
	AuthorizedAt    time.Time
	ReplicatesFiles bool
	Active          bool
}
