// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package federationdb

import (
	"context"

	"uuid"
)

type Querier interface {
	// How many readers still allow the node to hold a copy, across the whole
	// instance. It is what refuses to forget a node somebody is still replicating
	// to, and it counts every reader because the catalogue is node-wide.
	CountActiveReplicaAuthorizationsForServer(ctx context.Context, serverID uuid.UUID) (int64, error)
	// Which nodes a reader allows to hold a copy of their data (RF16, UC15).
	//
	// Nothing here deletes. Revoking clears active, because the record that the
	// authorization once existed is what explains a peer that still holds data:
	// revocation stops the replication, it does not reach into another operator's
	// database.
	//
	// One row per (reader, node) pair, which the unique constraint enforces and
	// which is what makes a re-grant an update rather than a second history.
	CreateReplicaAuthorization(ctx context.Context, arg CreateReplicaAuthorizationParams) error
	// A peer, with the identifier the entity minted. is_local is false here and in
	// no other statement: EnsureLocalServer above is the only writer of the flag.
	CreateServer(ctx context.Context, arg CreateServerParams) error
	DeleteServer(ctx context.Context, id uuid.UUID) (int64, error)
	// The catalogue of nodes this instance knows, its own included (RF13, UC12).
	//
	// The catalogue is node-wide: federation.servers names no reader, and what is
	// per-reader is the permission in federation.user_replicas. Nothing here is
	// therefore scoped to a caller.
	//
	// Two columns are never written by an update. The domain identifies the row
	// across the federation, and is_local is what the partial unique index allows
	// exactly one row to claim; a statement that changed either would either
	// orphan the readers hosted here or make "is this reader local" unanswerable.
	// Create or refresh the row that says which node this is.
	//
	// The upsert is on the domain, and it rewrites what a redeployment may have
	// changed — the base URL and the JWKS location — while leaving the identifier
	// alone. That identifier is referenced by every reader hosted here, so a
	// statement that replaced it would orphan them.
	//
	// The certificate pin is deliberately absent. A node does not pin itself: it
	// publishes its pin in the discovery document, and what is stored here is what
	// peers were told, not what this node checks.
	//
	// If this node is renamed, the insert collides with the partial unique index
	// rather than leaving two rows claiming to be this instance — which is the
	// right outcome: a node whose domain changed has a catalogue that needs an
	// operator, not a second identity.
	EnsureLocalServer(ctx context.Context, arg EnsureLocalServerParams) (FederationServer, error)
	// Read by the pair rather than by the primary key, because that is what the
	// reader names: a node, and themselves. Revoked rows are returned, since
	// re-authorizing one writes that row rather than a second.
	GetReplicaAuthorizationByPair(ctx context.Context, arg GetReplicaAuthorizationByPairParams) (FederationUserReplica, error)
	// The lookup UC12 addresses by name, and the one that tells an addition from a
	// node the catalogue already holds.
	GetServerByDomain(ctx context.Context, domain string) (FederationServer, error)
	GetServerByID(ctx context.Context, id uuid.UUID) (FederationServer, error)
	// Newest decision first, with the identifier breaking the tie between two
	// granted in the same instant.
	ListReplicaAuthorizationsByUser(ctx context.Context, arg ListReplicaAuthorizationsByUserParams) ([]FederationUserReplica, error)
	// Ordered by domain, which is unique, so the list does not reshuffle between
	// two calls and needs no tie-break. Deactivated nodes are hidden unless asked
	// for: they are still known, and what they are not is replicated to.
	ListServers(ctx context.Context, includeInactive bool) ([]FederationServer, error)
	UpdateReplicaAuthorization(ctx context.Context, arg UpdateReplicaAuthorizationParams) (int64, error)
	// What a refresh learned, and whether the node takes part.
	UpdateServer(ctx context.Context, arg UpdateServerParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
