// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package federationdb

import (
	"context"

	"uuid"
)

type Querier interface {
	// How many readers still allow the node to hold a copy, across the whole
	// instance. It is what refuses to forget a node somebody is still replicating
	// to, and it counts every reader because the catalogue is node-wide.
	CountActiveReplicaAuthorizationsForServer(ctx context.Context, serverID uuid.UUID) (int64, error)
	// Which nodes a reader allows to hold a copy of their data (RF16, UC15).
	//
	// Nothing here deletes. Revoking clears active, because the record that the
	// authorization once existed is what explains a peer that still holds data:
	// revocation stops the replication, it does not reach into another operator's
	// database.
	//
	// One row per (reader, node) pair, which the unique constraint enforces and
	// which is what makes a re-grant an update rather than a second history.
	CreateReplicaAuthorization(ctx context.Context, arg CreateReplicaAuthorizationParams) error
	// A peer, with the identifier the entity minted. is_local is false here and in
	// no other statement: EnsureLocalServer above is the only writer of the flag.
	CreateServer(ctx context.Context, arg CreateServerParams) error
	// Forgetting a node, with both refusals in the statement rather than beside
	// it.
	//
	// is_local, because every reader hosted here references that row. And no
	// active authorization, because forgetting a node somebody still replicates to
	// would leave that reader unable to revoke a peer holding their data, which is
	// the whole of RN03 — and the foreign key cascades, so a delete that got past
	// the check would take their authorization with it rather than being refused
	// by the database.
	//
	// The caller reads the row first, so that it can say which of the two refused
	// it. This statement is what makes the refusal hold anyway: a check the caller
	// ran a moment earlier is a check something could have invalidated since.
	DeleteServerIfUnused(ctx context.Context, id uuid.UUID) (int64, error)
	// The catalogue of nodes this instance knows, its own included (RF13, UC12).
	//
	// The catalogue is node-wide: federation.servers names no reader, and what is
	// per-reader is the permission in federation.user_replicas. Nothing here is
	// therefore scoped to a caller.
	//
	// Two columns are never written by an update. The domain identifies the row
	// across the federation, and is_local is what the partial unique index allows
	// exactly one row to claim; a statement that changed either would either
	// orphan the readers hosted here or make "is this reader local" unanswerable.
	//
	// Every column list below ends with grpc_authority rather than reading in the
	// order the record is described in. It is the order the table has, since the
	// column was added by a later migration, and a list in any other order makes
	// sqlc generate a row struct per statement instead of reusing the one model —
	// four near-identical types, and a repository that maps each of them.
	// Create or refresh the row that says which node this is.
	//
	// The upsert is on the domain, and it rewrites what a redeployment may have
	// changed — the base URL and the JWKS location — while leaving the identifier
	// alone. That identifier is referenced by every reader hosted here, so a
	// statement that replaced it would orphan them.
	//
	// The certificate pin is deliberately absent. A node does not pin itself: it
	// publishes its pin in the discovery document, and what is stored here is what
	// peers were told, not what this node checks.
	//
	// The gRPC authority is written, and is the value this node advertises: a
	// catalogue where the local row could not say where the API answers would be
	// one a reader cannot read their own node out of (D06).
	//
	// If this node is renamed, the insert collides with the partial unique index
	// rather than leaving two rows claiming to be this instance — which is the
	// right outcome: a node whose domain changed has a catalogue that needs an
	// operator, not a second identity.
	EnsureLocalServer(ctx context.Context, arg EnsureLocalServerParams) (FederationServer, error)
	// Read by the pair rather than by the primary key, because that is what the
	// reader names: a node, and themselves. Revoked rows are returned, since
	// re-authorizing one writes that row rather than a second.
	GetReplicaAuthorizationByPair(ctx context.Context, arg GetReplicaAuthorizationByPairParams) (FederationUserReplica, error)
	GetServerByDomain(ctx context.Context, domain string) (FederationServer, error)
	// The lookup UC12 addresses by name, and the one that tells an addition from a
	// node the catalogue already holds.
	// The node that published a pin, for the calls whose caller is a peer.
	//
	// This instance's own row is excluded: it carries this node's own pin, and a
	// node that recognized itself as a peer would admit its own readers as somebody
	// else's. The column is not unique — two rows carry one pin only if an operator
	// recorded the same node under two domains — and the oldest is taken so that
	// the answer does not change when a second is added.
	GetServerByFingerprint(ctx context.Context, certificateFingerprint *string) (FederationServer, error)
	GetServerByID(ctx context.Context, id uuid.UUID) (FederationServer, error)
	// The same read, holding the row until the transaction ends.
	//
	// It is what makes the refusals of DeleteServerIfUnused and of the update that
	// clears `active` hold against a concurrent authorization. Both of those check
	// federation.user_replicas and then write federation.servers, and under READ
	// COMMITTED a subquery sees the snapshot its own statement began with — so an
	// authorization committed in between would be invisible to the check and lost
	// to the cascade.
	//
	// Every call that authorizes a node takes this lock first, and so does every
	// call that would refuse because of one. They then serialize on the row they
	// disagree about, and whichever arrives second sees what the first committed,
	// because each statement in a READ COMMITTED transaction takes a fresh
	// snapshot.
	//
	// Outside a transaction it locks nothing worth having: the lock is released
	// with the statement. The port says so.
	GetServerByIDForUpdate(ctx context.Context, id uuid.UUID) (FederationServer, error)
	// Newest decision first, with the identifier breaking the tie between two
	// granted in the same instant.
	ListReplicaAuthorizationsByUser(ctx context.Context, arg ListReplicaAuthorizationsByUserParams) ([]FederationUserReplica, error)
	// Ordered by domain, which is unique, so the list does not reshuffle between
	// two calls and needs no tie-break. Deactivated nodes are hidden unless asked
	// for: they are still known, and what they are not is replicated to.
	ListServers(ctx context.Context, includeInactive bool) ([]FederationServer, error)
	UpdateReplicaAuthorization(ctx context.Context, arg UpdateReplicaAuthorizationParams) (int64, error)
	// What a refresh learned, and whether the node takes part.
	UpdateServer(ctx context.Context, arg UpdateServerParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
