// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: replicas.sql

package federationdb

import (
	"context"
	"time"

	"uuid"
)

const countActiveReplicaAuthorizationsForServer = `-- name: CountActiveReplicaAuthorizationsForServer :one
SELECT count(*)
FROM federation.user_replicas
WHERE server_id = $1
  AND active
`

// How many readers still allow the node to hold a copy, across the whole
// instance. It is what refuses to forget a node somebody is still replicating
// to, and it counts every reader because the catalogue is node-wide.
func (q *Queries) CountActiveReplicaAuthorizationsForServer(ctx context.Context, serverID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveReplicaAuthorizationsForServer, serverID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReplicaAuthorization = `-- name: CreateReplicaAuthorization :exec

INSERT INTO federation.user_replicas (id, user_id, server_id, authorized_at, replicates_files, active)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateReplicaAuthorizationParams struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	ServerID        uuid.UUID
	AuthorizedAt    time.Time
	ReplicatesFiles bool
	Active          bool
}

// Which nodes a reader allows to hold a copy of their data (RF16, UC15).
//
// Nothing here deletes. Revoking clears active, because the record that the
// authorization once existed is what explains a peer that still holds data:
// revocation stops the replication, it does not reach into another operator's
// database.
//
// One row per (reader, node) pair, which the unique constraint enforces and
// which is what makes a re-grant an update rather than a second history.
func (q *Queries) CreateReplicaAuthorization(ctx context.Context, arg CreateReplicaAuthorizationParams) error {
	_, err := q.db.Exec(ctx, createReplicaAuthorization,
		arg.ID,
		arg.UserID,
		arg.ServerID,
		arg.AuthorizedAt,
		arg.ReplicatesFiles,
		arg.Active,
	)
	return err
}

const getReplicaAuthorizationByPair = `-- name: GetReplicaAuthorizationByPair :one
SELECT id, user_id, server_id, authorized_at, replicates_files, active
FROM federation.user_replicas
WHERE user_id = $1
  AND server_id = $2
`

type GetReplicaAuthorizationByPairParams struct {
	UserID   uuid.UUID
	ServerID uuid.UUID
}

// Read by the pair rather than by the primary key, because that is what the
// reader names: a node, and themselves. Revoked rows are returned, since
// re-authorizing one writes that row rather than a second.
func (q *Queries) GetReplicaAuthorizationByPair(ctx context.Context, arg GetReplicaAuthorizationByPairParams) (FederationUserReplica, error) {
	row := q.db.QueryRow(ctx, getReplicaAuthorizationByPair, arg.UserID, arg.ServerID)
	var i FederationUserReplica
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServerID,
		&i.AuthorizedAt,
		&i.ReplicatesFiles,
		&i.Active,
	)
	return i, err
}

const listReplicaAuthorizationsByUser = `-- name: ListReplicaAuthorizationsByUser :many
SELECT id, user_id, server_id, authorized_at, replicates_files, active
FROM federation.user_replicas
WHERE user_id = $1
  AND (active OR $2::boolean)
ORDER BY authorized_at DESC, id
`

type ListReplicaAuthorizationsByUserParams struct {
	UserID          uuid.UUID
	IncludeInactive bool
}

// Newest decision first, with the identifier breaking the tie between two
// granted in the same instant.
func (q *Queries) ListReplicaAuthorizationsByUser(ctx context.Context, arg ListReplicaAuthorizationsByUserParams) ([]FederationUserReplica, error) {
	rows, err := q.db.Query(ctx, listReplicaAuthorizationsByUser, arg.UserID, arg.IncludeInactive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FederationUserReplica{}
	for rows.Next() {
		var i FederationUserReplica
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ServerID,
			&i.AuthorizedAt,
			&i.ReplicatesFiles,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReplicaAuthorization = `-- name: UpdateReplicaAuthorization :execrows
UPDATE federation.user_replicas
SET authorized_at    = $2,
    replicates_files = $3,
    active           = $4
WHERE id = $1
`

type UpdateReplicaAuthorizationParams struct {
	ID              uuid.UUID
	AuthorizedAt    time.Time
	ReplicatesFiles bool
	Active          bool
}

func (q *Queries) UpdateReplicaAuthorization(ctx context.Context, arg UpdateReplicaAuthorizationParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateReplicaAuthorization,
		arg.ID,
		arg.AuthorizedAt,
		arg.ReplicatesFiles,
		arg.Active,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
