// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: servers.sql

package federationdb

import (
	"context"
	"time"

	"uuid"
)

const createServer = `-- name: CreateServer :exec
INSERT INTO federation.servers (id, domain, base_url, jwks_uri, certificate_fingerprint,
                                grpc_authority, is_local, discovered_at, active)
VALUES ($1, $2, $3, $4, $5, $6, false, $7, $8)
`

type CreateServerParams struct {
	ID                     uuid.UUID
	Domain                 string
	BaseUrl                string
	JwksUri                *string
	CertificateFingerprint *string
	GrpcAuthority          *string
	DiscoveredAt           *time.Time
	Active                 bool
}

// A peer, with the identifier the entity minted. is_local is false here and in
// no other statement: EnsureLocalServer above is the only writer of the flag.
func (q *Queries) CreateServer(ctx context.Context, arg CreateServerParams) error {
	_, err := q.db.Exec(ctx, createServer,
		arg.ID,
		arg.Domain,
		arg.BaseUrl,
		arg.JwksUri,
		arg.CertificateFingerprint,
		arg.GrpcAuthority,
		arg.DiscoveredAt,
		arg.Active,
	)
	return err
}

const deleteServer = `-- name: DeleteServer :execrows
DELETE FROM federation.servers
WHERE id = $1
`

func (q *Queries) DeleteServer(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteServer, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensureLocalServer = `-- name: EnsureLocalServer :one

INSERT INTO federation.servers (domain, base_url, jwks_uri, grpc_authority, is_local, discovered_at, active)
VALUES ($1, $2, $3, $4, true, now(), true)
ON CONFLICT (domain) DO UPDATE
    SET base_url       = EXCLUDED.base_url,
        jwks_uri       = EXCLUDED.jwks_uri,
        grpc_authority = EXCLUDED.grpc_authority,
        is_local       = true,
        active         = true
RETURNING id, domain, base_url, jwks_uri, certificate_fingerprint, is_local, discovered_at, active,
          grpc_authority
`

type EnsureLocalServerParams struct {
	Domain        string
	BaseUrl       string
	JwksUri       *string
	GrpcAuthority *string
}

// The catalogue of nodes this instance knows, its own included (RF13, UC12).
//
// The catalogue is node-wide: federation.servers names no reader, and what is
// per-reader is the permission in federation.user_replicas. Nothing here is
// therefore scoped to a caller.
//
// Two columns are never written by an update. The domain identifies the row
// across the federation, and is_local is what the partial unique index allows
// exactly one row to claim; a statement that changed either would either
// orphan the readers hosted here or make "is this reader local" unanswerable.
//
// Every column list below ends with grpc_authority rather than reading in the
// order the record is described in. It is the order the table has, since the
// column was added by a later migration, and a list in any other order makes
// sqlc generate a row struct per statement instead of reusing the one model —
// four near-identical types, and a repository that maps each of them.
// Create or refresh the row that says which node this is.
//
// The upsert is on the domain, and it rewrites what a redeployment may have
// changed — the base URL and the JWKS location — while leaving the identifier
// alone. That identifier is referenced by every reader hosted here, so a
// statement that replaced it would orphan them.
//
// The certificate pin is deliberately absent. A node does not pin itself: it
// publishes its pin in the discovery document, and what is stored here is what
// peers were told, not what this node checks.
//
// The gRPC authority is written, and is the value this node advertises: a
// catalogue where the local row could not say where the API answers would be
// one a reader cannot read their own node out of (D06).
//
// If this node is renamed, the insert collides with the partial unique index
// rather than leaving two rows claiming to be this instance — which is the
// right outcome: a node whose domain changed has a catalogue that needs an
// operator, not a second identity.
func (q *Queries) EnsureLocalServer(ctx context.Context, arg EnsureLocalServerParams) (FederationServer, error) {
	row := q.db.QueryRow(ctx, ensureLocalServer,
		arg.Domain,
		arg.BaseUrl,
		arg.JwksUri,
		arg.GrpcAuthority,
	)
	var i FederationServer
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.BaseUrl,
		&i.JwksUri,
		&i.CertificateFingerprint,
		&i.IsLocal,
		&i.DiscoveredAt,
		&i.Active,
		&i.GrpcAuthority,
	)
	return i, err
}

const getServerByDomain = `-- name: GetServerByDomain :one
SELECT id, domain, base_url, jwks_uri, certificate_fingerprint, is_local, discovered_at, active,
       grpc_authority
FROM federation.servers
WHERE domain = $1
`

// The lookup UC12 addresses by name, and the one that tells an addition from a
// node the catalogue already holds.
func (q *Queries) GetServerByDomain(ctx context.Context, domain string) (FederationServer, error) {
	row := q.db.QueryRow(ctx, getServerByDomain, domain)
	var i FederationServer
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.BaseUrl,
		&i.JwksUri,
		&i.CertificateFingerprint,
		&i.IsLocal,
		&i.DiscoveredAt,
		&i.Active,
		&i.GrpcAuthority,
	)
	return i, err
}

const getServerByID = `-- name: GetServerByID :one
SELECT id, domain, base_url, jwks_uri, certificate_fingerprint, is_local, discovered_at, active,
       grpc_authority
FROM federation.servers
WHERE id = $1
`

func (q *Queries) GetServerByID(ctx context.Context, id uuid.UUID) (FederationServer, error) {
	row := q.db.QueryRow(ctx, getServerByID, id)
	var i FederationServer
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.BaseUrl,
		&i.JwksUri,
		&i.CertificateFingerprint,
		&i.IsLocal,
		&i.DiscoveredAt,
		&i.Active,
		&i.GrpcAuthority,
	)
	return i, err
}

const listServers = `-- name: ListServers :many
SELECT id, domain, base_url, jwks_uri, certificate_fingerprint, is_local, discovered_at, active,
       grpc_authority
FROM federation.servers
WHERE active
   OR $1::boolean
ORDER BY domain
`

// Ordered by domain, which is unique, so the list does not reshuffle between
// two calls and needs no tie-break. Deactivated nodes are hidden unless asked
// for: they are still known, and what they are not is replicated to.
func (q *Queries) ListServers(ctx context.Context, includeInactive bool) ([]FederationServer, error) {
	rows, err := q.db.Query(ctx, listServers, includeInactive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FederationServer{}
	for rows.Next() {
		var i FederationServer
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.BaseUrl,
			&i.JwksUri,
			&i.CertificateFingerprint,
			&i.IsLocal,
			&i.DiscoveredAt,
			&i.Active,
			&i.GrpcAuthority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateServer = `-- name: UpdateServer :execrows
UPDATE federation.servers
SET base_url                = $2,
    jwks_uri                = $3,
    certificate_fingerprint = $4,
    grpc_authority          = $5,
    discovered_at           = $6,
    active                  = $7
WHERE id = $1
`

type UpdateServerParams struct {
	ID                     uuid.UUID
	BaseUrl                string
	JwksUri                *string
	CertificateFingerprint *string
	GrpcAuthority          *string
	DiscoveredAt           *time.Time
	Active                 bool
}

// What a refresh learned, and whether the node takes part.
func (q *Queries) UpdateServer(ctx context.Context, arg UpdateServerParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateServer,
		arg.ID,
		arg.BaseUrl,
		arg.JwksUri,
		arg.CertificateFingerprint,
		arg.GrpcAuthority,
		arg.DiscoveredAt,
		arg.Active,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
