#!/usr/bin/env sh
# Generates the keys the local federation needs, one set per node.
#
# Two keys per node, and they answer different questions. The node certificate
# is what a peer's mTLS is checked against (RNF08); it is self-signed, and that
# is not a shortcut — two nodes belong to two operators and share no authority,
# so what identifies a peer is the public key it published in its discovery
# document and never a chain (C12). The signing key is what the node's access
# tokens are signed with, and its public half is what /.well-known/jwks.json
# publishes (RNF11).
#
# The loopback address is a subject alternative name beside the domain, because
# the same certificate answers two callers: a peer inside the network dials the
# domain, and a device outside it — quirectl, the end-to-end suites — dials the
# port compose published on the host. A certificate that named only the domain
# would be one the second caller could not verify.
#
# Nothing here is committed. A private key in a repository is a private key in
# every clone of it, and these are regenerated by anybody who runs `make
# dev-up` — which is also what makes them worthless to steal.
set -eu

directory="${1:?usage: dev-certs.sh <directory> <domain>...}"
shift

command -v openssl >/dev/null 2>&1 || {
    echo "dev-certs: openssl is not installed, and these keys are what the local federation is trusted by" >&2
    exit 1
}

mkdir -p "$directory"
chmod 755 "$directory"

# The keys are mounted into a container that runs as an unprivileged user of
# its own, and a mount keeps the permissions of the host file, so a key kept at
# 600 for the developer is a key the node cannot read. They are world-readable
# for that reason and it costs nothing: they authenticate two containers to
# each other on one machine, they are regenerated by anybody who clones this,
# and no deployment that matters ever sees them.

for domain in "$@"; do
    certificate="$directory/$domain.crt.pem"
    key="$directory/$domain.key.pem"
    signing="$directory/$domain.signing.pem"

    # Idempotent on purpose: `make dev-up` runs this every time, and
    # regenerating the keys would change the pin under a catalogue that had
    # already recorded it — which is the one failure C12 exists to make
    # visible, and not one to inflict on a developer restarting a stack.
    if [ ! -f "$certificate" ] || [ ! -f "$key" ]; then
        openssl req -x509 -newkey ec -pkeyopt ec_paramgen_curve:prime256v1 \
            -nodes -days 3650 \
            -subj "/CN=$domain" \
            -addext "subjectAltName=DNS:$domain,IP:127.0.0.1" \
            -keyout "$key" -out "$certificate" 2>/dev/null
        chmod 644 "$key"
        echo "dev-certs: $domain has a node certificate"
    fi

    if [ ! -f "$signing" ]; then
        openssl ecparam -name prime256v1 -genkey -noout -out "$signing"
        chmod 644 "$signing"
        echo "dev-certs: $domain has a signing key"
    fi
done
