#!/usr/bin/env bash
# Brings up the local Kubernetes federation: two Quire nodes, each in its own
# namespace with its own gateway, database, object store and mail relay, both
# under QUIRE_ENV=production.
#
# It is the cluster counterpart of `make dev-up`, and it is a script rather than
# a document for the same reason that one is a compose file: a sequence nobody
# can run is a sequence that stops being true. Everything it does is idempotent,
# so running it again against a cluster that is already up is how a change to
# the manifests is applied.
#
# What it deliberately does not do is put a key in this repository. The signing
# keys, the database passwords and the object store credentials are generated
# here, live in the cluster, and are regenerated by whoever runs this next.
set -euo pipefail

cluster="${1:-quire}"
repository="$(cd "$(dirname "$0")/.." && pwd)"

# Pinned, because a cluster that installed whatever was newest would be a
# cluster nobody can reproduce, and both of these are load-bearing: the mesh
# terminates one port and passes another through, and the authority signs every
# certificate in it.
cert_manager_version="v1.19.2"

# The two nodes, and the ports each is reached on from the host. The node ports
# are what deploy/kind/cluster.yaml maps, so the two files have to agree; they
# are listed here in the order namespace, domain, https, federation, database.
nodes=(
    "quire-a quire-a.example origin 30443 30943 30532"
    "quire-b quire-b.example replica 30444 30944 30533"
)

say() { printf '\033[36mkind-up:\033[0m %s\n' "$*"; }

require() {
    command -v "$1" >/dev/null 2>&1 || {
        echo "kind-up: $1 is not installed, and $2" >&2
        exit 1
    }
}

require kind "the cluster is one"
require kubectl "everything below applies through it"
require istioctl "the mesh is what terminates one port and passes another through"
require docker "the images are built and loaded through it"
require openssl "the signing keys are generated with it"

# --- the cluster -------------------------------------------------------------

if kind get clusters 2>/dev/null | grep -qx "$cluster"; then
    say "the cluster $cluster is already up"
else
    say "creating the cluster $cluster"
    kind create cluster --name "$cluster" --config "$repository/deploy/kind/cluster.yaml"
fi

kubectl config use-context "kind-$cluster" >/dev/null

# --- the mesh and the authority ----------------------------------------------

if kubectl get namespace istio-system >/dev/null 2>&1; then
    say "istio is already installed"
else
    say "installing istio"
    # minimal, which is istiod and nothing else. The shared ingress gateway the
    # default profile installs would go unused: each Quire node owns the gateway
    # that answers for its domain, because two nodes in a federation belong to
    # two operators who share no authority and would share no ingress.
    istioctl install --set profile=minimal -y
fi

say "installing cert-manager $cert_manager_version"
kubectl apply -f \
    "https://github.com/cert-manager/cert-manager/releases/download/${cert_manager_version}/cert-manager.yaml"
kubectl -n cert-manager rollout status deployment/cert-manager-webhook --timeout=5m

say "applying the cluster authority"
# The webhook takes a moment to start answering after the rollout reports
# ready, and an issuer applied into that window is refused with a connection
# error rather than a validation one.
until kubectl apply -k "$repository/deploy/k8s/certmanager/cluster" >/dev/null 2>&1; do
    sleep 2
done
kubectl apply -k "$repository/deploy/k8s/certmanager/cluster"

# --- the images --------------------------------------------------------------

say "building the images"
make -C "$repository" images >/dev/null

image="$(make -C "$repository" -s image-name | head -1)"
migrate_image="$(make -C "$repository" -s image-name | tail -1)"
tag="${image##*:}"

say "loading $image and $migrate_image into the cluster"
kind load docker-image --name "$cluster" "$image" "$migrate_image"

# --- resolution --------------------------------------------------------------

# A node is discovered by fetching a document from a path of its domain, so
# quire-a.example has to resolve — inside the cluster for the two nodes to find
# each other, and on the host for the end-to-end suite to reach either.
#
# Inside, it is a CoreDNS rewrite rather than an address: the gateway's own
# service name is what the domain should mean, and an address written down here
# is one that changes when a service is recreated.
mkdir -p "$repository/bin"

say "teaching the cluster to resolve the two domains"
rewrites=""
for entry in "${nodes[@]}"; do
    read -r namespace domain _ _ _ _ <<<"$entry"
    rewrites="$rewrites rewrite name $domain quire-gateway.$namespace.svc.cluster.local"
done

# The rewrite has to sit above the kubernetes plugin, which is what the
# insertion below finds. It is done in Python rather than in sed because a sed
# replacement cannot carry the newlines this one needs, and a Corefile written
# by an almost-right substitution is a cluster with no DNS at all.
kubectl -n kube-system get configmap coredns -o jsonpath='{.data.Corefile}' |
    python3 -c '
import sys

corefile = sys.stdin.read()
rewrites = [line.strip() for line in sys.argv[1].split("rewrite name") if line.strip()]
lines = corefile.splitlines()
out = []

for line in lines:
    stripped = line.strip()
    if stripped.startswith("kubernetes "):
        indent = line[: len(line) - len(line.lstrip())]
        for rewrite in rewrites:
            statement = indent + "rewrite name " + rewrite
            if statement not in lines:
                out.append(statement)
    out.append(line)

sys.stdout.write("\n".join(out) + "\n")
' "$rewrites" >"$repository/bin/Corefile"

kubectl -n kube-system create configmap coredns \
    --from-file=Corefile="$repository/bin/Corefile" \
    --dry-run=client -o yaml | kubectl apply -f - >/dev/null
kubectl -n kube-system rollout restart deployment/coredns >/dev/null

# On the host it is /etc/hosts, which this script will not edit: a script that
# needed a password in order to bring up a test cluster is a script nobody
# should run. It says what to add and carries on, because everything except the
# end-to-end suite works without it.
if ! getent hosts quire-a.example >/dev/null 2>&1; then
    say "quire-a.example does not resolve on this machine. The end-to-end suite needs it:"
    printf '\n    echo "127.0.0.1 quire-a.example quire-b.example" | sudo tee -a /etc/hosts\n\n'
fi

# --- the nodes ---------------------------------------------------------------

# patch_node_port publishes one port of one service on the node, at the number
# deploy/kind/cluster.yaml maps to the host.
patch_node_port() {
    local namespace="$1" service="$2" port="$3" node_port="$4"

    kubectl -n "$namespace" patch service "$service" --type=json -p "$(
        cat <<JSON
[
  {"op": "replace", "path": "/spec/type", "value": "NodePort"},
  {"op": "replace", "path": "/spec/ports/$(port_index "$namespace" "$service" "$port")/nodePort",
   "value": $node_port}
]
JSON
    )" >/dev/null
}

# port_index finds a named port by its position, which is what a JSON patch
# addresses it by.
port_index() {
    kubectl -n "$1" get service "$2" -o json |
        python3 -c "import json,sys;print([p['name'] for p in json.load(sys.stdin)['spec']['ports']].index('$3'))"
}

# The credentials, generated here and written straight into the cluster. They
# are recreated on every run, which is why the node is restarted below: a pod
# holding the previous password is a pod that stops being able to connect.
secrets() {
    local namespace="$1" domain="$2"
    local password signing_key

    password="$(openssl rand -hex 24)"
    signing_key="$(openssl ecparam -name prime256v1 -genkey -noout 2>/dev/null |
        openssl pkcs8 -topk8 -nocrypt 2>/dev/null)"

    apply_secret "$namespace" quire-postgres \
        "POSTGRES_PASSWORD=$password"

    apply_secret "$namespace" quire-database \
        "QUIRE_DATABASE_URL=postgres://quire:$password@quire-postgres:5432/quire?sslmode=disable"

    apply_secret "$namespace" quire-signing-key \
        "QUIRE_AUTH_PRIVATE_KEY_PEM=$signing_key" \
        "QUIRE_AUTH_KEY_ID=$namespace-$(date +%Y-%m)"

    apply_secret "$namespace" quire-storage \
        "QUIRE_STORAGE_MINIO_ENDPOINT=quire-storage:9000" \
        "QUIRE_STORAGE_MINIO_ACCESS_KEY_ID=quire" \
        "QUIRE_STORAGE_MINIO_SECRET_ACCESS_KEY=$(openssl rand -hex 20)"

    # The relay is reached over STARTTLS, which production requires: the
    # credential being submitted is the one that replaces a password.
    apply_secret "$namespace" quire-mail \
        "QUIRE_MAIL_SMTP_HOST=quire-mail" \
        "QUIRE_MAIL_SMTP_PORT=587" \
        "QUIRE_MAIL_SMTP_SECURITY=starttls" \
        "QUIRE_MAIL_FROM_ADDRESS=no-reply@$domain" \
        "QUIRE_MAIL_FROM_NAME=Quire"
}

# apply_secret writes one secret, replacing whatever was there. The literals go
# through a here-document rather than a command line so that a key never
# appears in the process table, where every other user of the machine can read
# it.
apply_secret() {
    local namespace="$1" name="$2"
    shift 2

    local arguments=()
    for pair in "$@"; do
        arguments+=(--from-literal="$pair")
    done

    kubectl -n "$namespace" create secret generic "$name" "${arguments[@]}" \
        --dry-run=client -o yaml | kubectl apply -f - >/dev/null
}

for entry in "${nodes[@]}"; do
    read -r namespace domain overlay https_port federation_port database_port <<<"$entry"

    say "deploying $domain into $namespace"

    # The namespace before the secrets, because a secret has to land in one, and
    # the overlay is what declares it.
    kubectl create namespace "$namespace" --dry-run=client -o yaml | kubectl apply -f - >/dev/null
    kubectl label namespace "$namespace" istio-injection=enabled --overwrite >/dev/null

    secrets "$namespace" "$domain"

    # The schema job is immutable in the fields that matter, so a re-run against
    # a changed migration would be refused. Deleting it is the deliberate act
    # its own manifest describes, and here the deliberation is that this script
    # is what applies a schema change to a throwaway cluster.
    kubectl -n "$namespace" delete job quire-migrate --ignore-not-found >/dev/null

    kubectl kustomize "$repository/deploy/k8s/overlays/$overlay" |
        sed -e "s|ghcr.io/anthonyvsmuller/quired:dev|$image|g" \
            -e "s|ghcr.io/anthonyvsmuller/quire-migrate:dev|$migrate_image|g" |
        kubectl apply -f - >/dev/null

    # Three services reach the host, and they are patched here rather than
    # declared as NodePort in the overlay: a published port is a fact about this
    # machine, and an overlay that carried one would be an overlay nobody could
    # deploy twice in a cluster.
    patch_node_port "$namespace" quire-gateway https "$https_port"
    patch_node_port "$namespace" quire-gateway tls-federation "$federation_port"
    patch_node_port "$namespace" quire-postgres tcp-postgres "$database_port"

    # The credentials were rewritten above, so whatever is running is holding
    # the previous ones.
    kubectl -n "$namespace" rollout restart deployment/quire >/dev/null
done

say "waiting for both nodes"
for entry in "${nodes[@]}"; do
    read -r namespace _ _ _ _ _ <<<"$entry"

    kubectl -n "$namespace" rollout status deployment/quire-gateway --timeout=5m
    kubectl -n "$namespace" wait --for=condition=complete job/quire-migrate --timeout=5m
    kubectl -n "$namespace" rollout status deployment/quire --timeout=5m
done

# --- what the suite needs ----------------------------------------------------

# The authority every certificate in the cluster is signed by, written where the
# end-to-end suite and quirectl can point at it. It is not a secret — it is the
# public half — and it is not in the repository either, because it is generated
# per cluster.
mkdir -p "$repository/bin/kind"
kubectl -n cert-manager get secret quire-ca -o jsonpath='{.data.tls\.crt}' |
    base64 -d >"$repository/bin/kind/ca.crt"

say "the federation is up"
say "the authority is in bin/kind/ca.crt, and \`make test-kind\` runs the suite against it"
