-- The position allocator, one row per reader (C08 in docs/tcc-corrections.md).
--
-- The allocation itself is not here. It is the data-modifying CTE of
-- AppendOperation in operations.sql, because the whole guarantee is that the
-- row lock the upsert takes is held until the operation it numbered has
-- committed — and a statement that allocated on its own could be called from a
-- transaction that then did something else, which is exactly the failure the
-- correction removes. What is left here is the read.

-- This node's last allocated position for a reader, and zero for a reader
-- whose log is empty.
--
-- A device that has just pushed learns from it whether there is anything to
-- pull, without asking. It is the head of the log and not the position of the
-- last operation returned by a page, and the contract keeps the two apart for
-- that reason.
--
-- The scalar subquery is what makes an absent stream a zero rather than an
-- empty result: a reader whose log has never been written has the same head as
-- one whose log is empty, and a caller should not have to tell them apart.
-- name: GetStreamHead :one
SELECT COALESCE((SELECT last_position FROM sync.streams WHERE user_id = $1), 0)::bigint AS head;
