// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: credentials.sql

package identitydb

import (
	"context"
	"time"

	"uuid"
)

const consumeCredential = `-- name: ConsumeCredential :execrows
UPDATE identity.credentials
SET consumed = true
WHERE id = $1
  AND NOT consumed
`

// The check and the write are one statement, and the NOT consumed in the WHERE
// clause is what makes it one. Two devices presenting the same refresh
// credential at the same instant both find it unconsumed if they read first and
// write after, and both are answered with a session; here the second UPDATE
// matches no row, reports zero, and the caller refuses it.
func (q *Queries) ConsumeCredential(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, consumeCredential, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumeCredentialsForDevice = `-- name: ConsumeCredentialsForDevice :execrows
UPDATE identity.credentials
SET consumed = true
WHERE device_id = $1
  AND NOT consumed
`

// What unbinding a device means for the sessions it holds.
func (q *Queries) ConsumeCredentialsForDevice(ctx context.Context, deviceID *uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, consumeCredentialsForDevice, deviceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumeCredentialsForUser = `-- name: ConsumeCredentialsForUser :execrows
UPDATE identity.credentials
SET consumed = true
WHERE user_id = $1
  AND kind = $2
  AND NOT consumed
`

type ConsumeCredentialsForUserParams struct {
	UserID uuid.UUID
	Kind   string
}

// What resetting a password means for every session of every device: the reader
// is recovering precisely because they may not be the only party holding the
// old one.
func (q *Queries) ConsumeCredentialsForUser(ctx context.Context, arg ConsumeCredentialsForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeCredentialsForUser, arg.UserID, arg.Kind)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createCredential = `-- name: CreateCredential :exec

INSERT INTO identity.credentials (id, user_id, device_id, kind, token_hash, expires_at, consumed)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateCredentialParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	DeviceID  *uuid.UUID
	Kind      string
	TokenHash string
	ExpiresAt time.Time
	Consumed  bool
}

// The temporary credentials this node issues (RF07, RF08, RF09; UC07, UC08).
//
// Only digests are stored, never the credential itself, so every statement here
// addresses a row by the digest of what a caller presented or by a key learned
// from it. A dump of this table then hands an attacker nothing to replay.
func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) error {
	_, err := q.db.Exec(ctx, createCredential,
		arg.ID,
		arg.UserID,
		arg.DeviceID,
		arg.Kind,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.Consumed,
	)
	return err
}

const deleteExpiredCredentials = `-- name: DeleteExpiredCredentials :execrows
DELETE FROM identity.credentials
WHERE expires_at < $1
`

// Housekeeping, and nothing depends on it running: an expired credential is
// refused whether or not its row is still there.
func (q *Queries) DeleteExpiredCredentials(ctx context.Context, expiresAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredCredentials, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCredentialByTokenHash = `-- name: GetCredentialByTokenHash :one
SELECT id, user_id, device_id, kind, token_hash, expires_at, consumed
FROM identity.credentials
WHERE token_hash = $1
`

func (q *Queries) GetCredentialByTokenHash(ctx context.Context, tokenHash string) (IdentityCredential, error) {
	row := q.db.QueryRow(ctx, getCredentialByTokenHash, tokenHash)
	var i IdentityCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.Kind,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.Consumed,
	)
	return i, err
}
