// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package identitydb

import (
	"context"
	"time"

	"uuid"
)

const createDevice = `-- name: CreateDevice :exec

INSERT INTO identity.devices (id, user_id, name, platform, last_synced_at, active)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateDeviceParams struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Name         string
	Platform     string
	LastSyncedAt *time.Time
	Active       bool
}

// The appliances bound to a reader's account (RF11, UC10).
//
// Nothing here deletes. Unbinding a device clears identity.devices.active,
// because every operation the device authored still names its id and a vector
// clock entry pointing at a device nobody can resolve cannot be explained to
// the reader, audited, or checked against RN10.
func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) error {
	_, err := q.db.Exec(ctx, createDevice,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Platform,
		arg.LastSyncedAt,
		arg.Active,
	)
	return err
}

const getDeviceByID = `-- name: GetDeviceByID :one
SELECT id, user_id, name, platform, last_synced_at, active
FROM identity.devices
WHERE id = $1
`

func (q *Queries) GetDeviceByID(ctx context.Context, id uuid.UUID) (IdentityDevice, error) {
	row := q.db.QueryRow(ctx, getDeviceByID, id)
	var i IdentityDevice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Platform,
		&i.LastSyncedAt,
		&i.Active,
	)
	return i, err
}

const listDevicesByUser = `-- name: ListDevicesByUser :many
SELECT id, user_id, name, platform, last_synced_at, active
FROM identity.devices
WHERE user_id = $1
  AND (active OR $2::boolean)
ORDER BY name, id
`

type ListDevicesByUserParams struct {
	UserID          uuid.UUID
	IncludeInactive bool
}

// Ordered by name, so that the list RF11 makes auditable does not reshuffle
// between two calls; the id breaks the tie, since two appliances may well be
// called the same thing. Unbound devices are hidden unless asked for: their
// rows survive revocation, and they are what explains a clock entry the reader
// no longer recognizes.
func (q *Queries) ListDevicesByUser(ctx context.Context, arg ListDevicesByUserParams) ([]IdentityDevice, error) {
	rows, err := q.db.Query(ctx, listDevicesByUser, arg.UserID, arg.IncludeInactive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityDevice{}
	for rows.Next() {
		var i IdentityDevice
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Platform,
			&i.LastSyncedAt,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDevice = `-- name: UpdateDevice :execrows
UPDATE identity.devices
SET name           = $2,
    last_synced_at = $3,
    active         = $4
WHERE id = $1
`

type UpdateDeviceParams struct {
	ID           uuid.UUID
	Name         string
	LastSyncedAt *time.Time
	Active       bool
}

func (q *Queries) UpdateDevice(ctx context.Context, arg UpdateDeviceParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateDevice,
		arg.ID,
		arg.Name,
		arg.LastSyncedAt,
		arg.Active,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
