// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package identitydb

import (
	"time"

	"uuid"
)

type IdentityCredential struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	DeviceID  *uuid.UUID
	Kind      string
	TokenHash string
	ExpiresAt time.Time
	Consumed  bool
}

type IdentityDevice struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Name         string
	Platform     string
	LastSyncedAt *time.Time
	Active       bool
}

type IdentityUser struct {
	ID             uuid.UUID
	OriginServerID uuid.UUID
	LocalName      string
	DisplayName    string
	Email          *string
	PasswordHash   *string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
