// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package identitydb

import (
	"context"
	"time"

	"uuid"
)

type Querier interface {
	// The check and the write are one statement, and the NOT consumed in the WHERE
	// clause is what makes it one. Two devices presenting the same refresh
	// credential at the same instant both find it unconsumed if they read first and
	// write after, and both are answered with a session; here the second UPDATE
	// matches no row, reports zero, and the caller refuses it.
	ConsumeCredential(ctx context.Context, id uuid.UUID) (int64, error)
	// What unbinding a device means for the sessions it holds.
	ConsumeCredentialsForDevice(ctx context.Context, deviceID *uuid.UUID) (int64, error)
	// What resetting a password means for every session of every device: the reader
	// is recovering precisely because they may not be the only party holding the
	// old one.
	ConsumeCredentialsForUser(ctx context.Context, arg ConsumeCredentialsForUserParams) (int64, error)
	// The temporary credentials this node issues (RF07, RF08, RF09; UC07, UC08).
	//
	// Only digests are stored, never the credential itself, so every statement here
	// addresses a row by the digest of what a caller presented or by a key learned
	// from it. A dump of this table then hands an attacker nothing to replay.
	CreateCredential(ctx context.Context, arg CreateCredentialParams) error
	// The appliances bound to a reader's account (RF11, UC10).
	//
	// Nothing here deletes. Unbinding a device clears identity.devices.active,
	// because every operation the device authored still names its id and a vector
	// clock entry pointing at a device nobody can resolve cannot be explained to
	// the reader, audited, or checked against RN10.
	CreateDevice(ctx context.Context, arg CreateDeviceParams) error
	// The readers this node knows (RF06, UC06, UC14).
	//
	// Every statement that reads a reader by something other than the primary key
	// takes the origin server as a parameter. RN09 makes the identifier unique on
	// the pair and the address unique only within the origin server, so a lookup
	// that omitted it would answer with a reader of another node — and on a node
	// that replicates for a peer, rows of both kinds sit in this table.
	CreateUser(ctx context.Context, arg CreateUserParams) error
	// Housekeeping, and nothing depends on it running: an expired credential is
	// refused whether or not its row is still there.
	DeleteExpiredCredentials(ctx context.Context, expiresAt time.Time) (int64, error)
	DeleteUser(ctx context.Context, id uuid.UUID) (int64, error)
	// This node's own row in the catalogue of servers (RF13).
	//
	// The catalogue belongs to the federation slice, and the query is here because
	// the identity slice needs it before that slice exists: UC14 binds a reader to
	// the node they registered with, and identity.users.origin_server_id has to
	// point at something. Phase 6 takes the table over; what this file writes is
	// the one row it will already find there.
	// Create or refresh the row that says which node this is.
	//
	// The upsert is on the domain, which is what identifies a node across the
	// federation, and it rewrites what a redeployment may have changed — the base
	// URL and the JWKS location — while leaving the identifier alone. That
	// identifier is referenced by every reader hosted here, so a statement that
	// replaced it would orphan them.
	//
	// A partial unique index allows one row to claim is_local. If this node is
	// renamed, the insert collides with it rather than leaving two rows claiming to
	// be this instance — which is the right outcome: a node whose domain changed
	// has a catalogue that needs an operator, not a second identity.
	EnsureLocalServer(ctx context.Context, arg EnsureLocalServerParams) (uuid.UUID, error)
	GetCredentialByTokenHash(ctx context.Context, tokenHash string) (IdentityCredential, error)
	GetDeviceByID(ctx context.Context, id uuid.UUID) (IdentityDevice, error)
	// Folded on both sides, because the unique index enforcing RN09 is over
	// lower(email): a lookup that compared the stored capitalization would miss the
	// row that a second registration is about to collide with, and would report the
	// address free right up to the insert that fails.
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (IdentityUser, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (IdentityUser, error)
	GetUserByLocalName(ctx context.Context, arg GetUserByLocalNameParams) (IdentityUser, error)
	// Ordered by name, so that the list RF11 makes auditable does not reshuffle
	// between two calls; the id breaks the tie, since two appliances may well be
	// called the same thing. Unbound devices are hidden unless asked for: their
	// rows survive revocation, and they are what explains a clock entry the reader
	// no longer recognizes.
	ListDevicesByUser(ctx context.Context, arg ListDevicesByUserParams) ([]IdentityDevice, error)
	UpdateDevice(ctx context.Context, arg UpdateDeviceParams) (int64, error)
	// Only the four columns UC06 makes writable. The local name and the origin
	// server are the identity itself: changing the first is registering somebody
	// else, and changing the second is the migration of RF17, which rewrites the
	// column deliberately and elsewhere.
	//
	// :execrows, so that a caller can tell a reader who was updated from one who no
	// longer exists. An UPDATE matching nothing is not an error to PostgreSQL.
	UpdateUser(ctx context.Context, arg UpdateUserParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
