// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package identitydb

import (
	"context"
	"time"

	"uuid"
)

const createUser = `-- name: CreateUser :exec

INSERT INTO identity.users (
    id, origin_server_id, local_name, display_name, email, password_hash, migrated_from,
    created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateUserParams struct {
	ID             uuid.UUID
	OriginServerID uuid.UUID
	LocalName      string
	DisplayName    string
	Email          *string
	PasswordHash   *string
	MigratedFrom   *string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

// The readers this node knows (RF06, UC06, UC14).
//
// Every statement that reads a reader by something other than the primary key
// takes the origin server as a parameter. RN09 makes the identifier unique on
// the pair and the address unique only within the origin server, so a lookup
// that omitted it would answer with a reader of another node — and on a node
// that replicates for a peer, rows of both kinds sit in this table.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.OriginServerID,
		arg.LocalName,
		arg.DisplayName,
		arg.Email,
		arg.PasswordHash,
		arg.MigratedFrom,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM identity.users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, origin_server_id, local_name, display_name, email, password_hash,
       created_at, updated_at, migrated_from
FROM identity.users
WHERE origin_server_id = $1
  AND lower(email) = lower($2::text)
`

type GetUserByEmailParams struct {
	OriginServerID uuid.UUID
	Email          string
}

// Folded on both sides, because the unique index enforcing RN09 is over
// lower(email): a lookup that compared the stored capitalization would miss the
// row that a second registration is about to collide with, and would report the
// address free right up to the insert that fails.
func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, arg.OriginServerID, arg.Email)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.OriginServerID,
		&i.LocalName,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MigratedFrom,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, origin_server_id, local_name, display_name, email, password_hash,
       created_at, updated_at, migrated_from
FROM identity.users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.OriginServerID,
		&i.LocalName,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MigratedFrom,
	)
	return i, err
}

const getUserByLocalName = `-- name: GetUserByLocalName :one
SELECT id, origin_server_id, local_name, display_name, email, password_hash,
       created_at, updated_at, migrated_from
FROM identity.users
WHERE origin_server_id = $1
  AND local_name = $2
`

type GetUserByLocalNameParams struct {
	OriginServerID uuid.UUID
	LocalName      string
}

func (q *Queries) GetUserByLocalName(ctx context.Context, arg GetUserByLocalNameParams) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, getUserByLocalName, arg.OriginServerID, arg.LocalName)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.OriginServerID,
		&i.LocalName,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MigratedFrom,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :execrows
UPDATE identity.users
SET display_name  = $2,
    email         = $3,
    password_hash = $4,
    updated_at    = $5
WHERE id = $1
`

type UpdateUserParams struct {
	ID           uuid.UUID
	DisplayName  string
	Email        *string
	PasswordHash *string
	UpdatedAt    time.Time
}

// Only the four columns UC06 makes writable. The local name and the origin
// server are the identity itself: changing the first is registering somebody
// else, and changing the second is the migration of RF17, which rewrites the
// column deliberately and elsewhere.
//
// :execrows, so that a caller can tell a reader who was updated from one who no
// longer exists. An UPDATE matching nothing is not an error to PostgreSQL.
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.DisplayName,
		arg.Email,
		arg.PasswordHash,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
